homepage/urls.py
from django.urls import path 
from . import views
from django.contrib import admin

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('reach-me/', views.reachme, name='reachme'),
    path('experience/', views.experience, name='experience'),
    path('addfriend/', views.addfriend, name='addfriend'),
    path('seefriend/', views.seefriend, name='seefriend'),
]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

from django.forms import ModelForm

#Create your models here.
class ClassYear(models.Model):
    BATCH_CHOICES= [('Maung (2019)', 'Maung (2019)'),
    ('Quanta (2018)', 'Quanta (2018)'),
    ('Tarung (2017)', 'Tarung (2017)'),
    ('Omega (2016)', 'Omega (2016)'),
    ('Others', 'Others')]
    batch = models.CharField(max_length=255, choices=BATCH_CHOICES, default='NULL')

    def __str__(self):
        return self.batch

class Friends(models.Model):
    name = models.CharField(max_length=255, primary_key=True, default='')
    ClassYear = models.ForeignKey(ClassYear, on_delete=models.CASCADE, default='Fasilkom')
    hobby = models.CharField(max_length=255)
    food = models.CharField(max_length=255)
    drink = models.CharField(max_length=255)

    def __str__(self):
        return self.name

homepage/forms.py
from django import forms
from .models import Friends, ClassYear

class FriendForm(forms.ModelForm):
    class Meta:
        model = Friends
        fields = ['name', 'ClassYear', 'hobby', 'food', 'drink']
        labels = {'name': 'Name',
                'ClassYear': 'Batch',
                'hobby': 'Hobby',
                'food': 'Favorite Food',
                'drink': 'Favorite Drink'}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

homepage/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Friends, ClassYear
from . import forms


# Create your views here.
def home(request):
    return render(request, 'home.html')
    
def profile(request):
    return render(request, 'profile.html')

def experience(request):
    return render(request, 'experience.html')

def reachme(request):
    return render(request, 'reach-me.html')

def addfriend(request):
    if request.method == 'POST':
        form = forms.FriendForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('homepage:seefriend')
    else:
        form = forms.FriendForm()
    return render(request, 'addfriend.html', {'form': form})

def seefriend(request):
    friends = Friends.objects.all()
    classyear = ClassYear.objects.all()
    response = {'friends' : friends, 'classyear': classyear}
    return render(request, 'seefriend.html', response)

homepage/templates/addfriend.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Home</title>
  </head>
  <body style="background-image: url('/static/bg1.jpg'); background-size:cover;">
    <div class="containter">
      <div class="row" id="navbar">
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:home' %}">H O M E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:profile' %}">P R O F I L E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:experience' %}">E X P E R I E N C E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:reachme' %}">R E A C H <sp>  M E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:addfriend' %}">F R I E N D S</a>
        </div>
      </div>
    </div>
    
<title style="text-align: center;">Add Friends</title>
<br><br>
<h1 style="text-align: center;">Add Friends</h1>

<form method="post" action="{% url 'homepage:addfriend' %}">
    {% csrf_token %}
    <div style="margin-left: 10px; margin-right: 10px;">
    <div class="form-row">
        <div class="col-sm-1"></div>
        <div class="form-group col-sm-10">
            {% for fields in form %}
                {{ fields.label_tag }}
                <br>
                {{ fields }}
            {% endfor %}
        </div>
    </div>
    <div class="form-row">
        <input style="align-content: center; margin-left: auto; margin-right: auto;" id="submitBtn" type="submit" class="btn btn-primary" value="Add">
    </div>
</form>
</div>

 <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/experience.html
 <!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Profile</title>
  </head>
  <body style="background: url('/static/bg1.jpg'); background-size:cover;">
    <div class="containter">
      <div class="row" id="navbar">
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:home' %}">H O M E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:profile' %}">P R O F I L E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:experience' %}">E X P E R I E N C E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:reachme' %}">R E A C H <sp>  M E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:addfriend' %}">F R I E N D S</a>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6">
          <div class="porto-wrapper-2">
            <div class="porto-title">
              <p class="porto-title-text">Organizational Experience</p>
            </div>
            <div class="porto-bar-wrapper-2">
              <div class="porto-bar text-center" id="organization">
              <div class="org-exp-wrapper">
                <div class="org-exp">
                  <img src="{% static './dpm.png' %}" alt="" height="50px" width="auto" class="float-left">
                  <p class="org-text">DPM Fasilkom UI
                  <br>Head of Public Relations</p>
              </div>
                  <div class="org-exp">
                  <img src="{% static './bem.png' %}" alt="" height="50px" width="auto" class="float-left">
                  <p class="org-text">BEM Fasilkom UI
                  <br>Project officer of WisGen</p>
              </div>
              <div class="org-exp">
                  <img src="{% static './LOGOPEREK.jpg' %}" alt="" height="50px" width="45" class="float-left">
                  <p class="org-text">Pesta Rakyat Komputer
                  <br>Secretary</p>
              </div>
                </div>
              </div>
            </div>
            </div>
            </div>

        <div class="col-md-6">
          <div class="porto-wrapper-3">
            <div class="porto-title">
              <p class="porto-title-text">Work Experience</p>
            </div>
            <div class="porto-bar-wrapper-3">
              <div class="porto-bar text-center" id="work">
              <div class="work-exp-wrapper">
                <div class="work-exp">
                  <img src="{% static './k.jpg' %}" alt="" height="50px" width="auto" class="float-left">
                  <p class="work-text">Kumon
                  <br>Part - time teacher</p>
              </div>
                </div>
              </div>
            </div>

          </div>
        </div>

      </div>
    </div>
   

  

    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/footer.html
<footer>
    <div style="text-align: center;font-family: Arial, Helvetica, sans-serif;">
      <h5>© 2020 Copyright Inez Zahra</h5>
    </div>
</footer>

homepage/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Home</title>
  </head>
  <body style="background-image: url('/static/bg1.jpg'); background-size:cover;">
    <div class="containter">
      <div class="row" id="navbar">
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:home' %}">H O M E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:profile' %}">P R O F I L E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:experience' %}">E X P E R I E N C E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:reachme' %}">R E A C H <sp>  M E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:addfriend' %}">F R I E N D S</a>
        </div>
      </div>
    </div>
   <div class="container">
    <div class="hello-world">
    <div class="turqbar-container">
      <div class="turqbar"></div>

    </div>
      <div class="heading-texts">
        <div class="text-wrapper">
          <h1 class="text-center title-text float-left">HELLO WORLD</h1>
          <h4 class="little-text">feel free to navigate through my website</h4>
        </div>

      </div>
    <div class="turqbar-container">
      <div class="turqbar2"></div>
      </div>
    </div>
    <h1 class="name-wrapper text-uppercase float-right">inez zahra</h1>
   </div>
  

    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/profile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Profile</title>
  </head>
  <body style="background: url('/static/bg1.jpg'); background-size:cover;">
    <div class="containter">
      <div class="row" id="navbar">
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:home' %}">H O M E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:profile' %}">P R O F I L E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:experience' %}">E X P E R I E N C E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:reachme' %}">R E A C H <sp>  M E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:addfriend' %}">F R I E N D S</a>
        </div>
      </div>
    </div>


    <div class="container-fluid">
      <div class="row">
        <div class="col-md-4">
          <div class="profile-summary">
            <img src="{% static 'Rectangle8.png' %}" alt="" srcset="" class="profile-img">
            <div class="summary-wrapper">
              <p class="summary-text">A computer science student who loves to explore and learn new things. Has an always curious nature and is fascinated by a lot of things.</p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="porto-wrapper">
            <div class="porto-title">
              <p class="porto-title-text">Skills & Proficiency</p>
            </div>
            <div class="porto-bar-wrapper">
              <div class="porto-bar text-center" id="skill">
                <div class="skill-wrapper">
                  <div class="skill-bar">
                    <div class="filled-skill" id="python">
                      <p>Python</p>
                    </div>
                  </div>
            <div class="skill-bar">
              <div class="filled-skill-gray" id="english">
                <p>English Language</p>
              </div>
            </div>
            <div class="skill-bar">
              <div class="filled-skill" id="design">
                <p>Design</p>
              </div>
            </div>
            <div class="skill-bar">
              <div class="filled-skill-gray" id="java">
                <p>Java</p>
              </div>
            </div>
            <div class="skill-bar">
              <div class="filled-skill" id="teamwork">
                <p>Teamwork</p>
              </div>
            </div>
            <div class="skill-bar">
              <div class="filled-skill-gray" id="thinking">
                <p>Analytical Thinking</p>
              </div>
            </div>
            </div>
            </div>


            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="porto-wrapper">
            <div class="porto-title">
              <p class="porto-title-text">Educational Background</p>
            </div>
            <div class="porto-bar-wrapper">
              <div class="porto-bar text-center" id="education">
              <div class="school-exp-wrapper">
                <div class="school-exp">
                  <img src="{% static 'ui.png' %}" alt="" height="50px" width="auto" class="float-left">
                  <p class="edu-text">Universitas Indonesia
                  <br>Faculty of Computer Science</p>
              </div>
                  <div class="school-exp">
                  <img src="{% static 'kb.jpeg' %}" alt="" height="50px" width="auto" class="float-left">
                  <p class="edu-text">Universitas Indonesia
                  <br>Faculty of Computer Science</p>
              </div>
              <div class="school-exp">
                  <img src="{% static 'lab.png' %}" alt="" height="50px" width="auto" class="float-left">
                  <p class="edu-text">Universitas Indonesia
                  <br>Faculty of Computer Science</p>
              </div>
              <div class="school-exp">
                  <img src="{% static 'bakti.jpg' %}" alt="" height="50px" width="auto" class="float-left">
                  <p class="edu-text">Universitas Indonesia
                  <br>Faculty of Computer Science</p>
              </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
   {%include 'footer.html'%}

  

    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/reach-me.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Home</title>
  </head>
  <body style="background: url('/static/bg1.jpg'); background-size:cover;">
    <div class="containter">
      <div class="row" id="navbar">
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:home' %}">H O M E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:profile' %}">P R O F I L E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:experience' %}">E X P E R I E N C E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:reachme' %}">R E A C H <sp>  M E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:addfriend' %}">F R I E N D S</a>
        </div>
      </div>
    </div>
   <div class="container">
    <div class="hello-world">
    <div class="turqbar-container">
      <div class="turqbar"></div>

    </div>
      <div class="heading-text">
        <div class="text-wrapper">
          <h4 class="little-text">+62 811 895 5554</h4>
          <h4 class="little-text">inezzahra.nabila@gmail.com</h4>
          <h4 class="little-text">linkedin</h4>

        </div>

      </div>
    <div class="turqbar-container">
      <div class="turqbar2"></div>
      </div>
    
  

    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/seefriend.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Home</title>
  </head>
  <body style="background-image: url('/static/bg1.jpg'); background-size:cover;">
    <div class="containter">
      <div class="row" id="navbar">
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:home' %}">H O M E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:profile' %}">P R O F I L E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:experience' %}">E X P E R I E N C E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:reachme' %}">R E A C H <sp>  M E</a>
        </div>
        <div class="col-sm text-center text">
          <a href="{% url 'homepage:addfriend' %}">F R I E N D S</a>
        </div>
      </div>
    </div>
    <title>See Friends</title>
<br><br>
<h1 id="profh1" style="text-align: center;">My Friends</h1>

<table id="friendtable" class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Batch</th>
        <th scope="col">Hobby</th>
        <th scope="col">Fav Food</th>
        <th scope="col">Fav Drink</th>
      </tr>
    </thead>
    <tbody>
      {% for friend in friendss %}
        <tr class="table-info">
          <td class="table-secondary">{{ friend.name }}</td>
          <td class="table-info">{{ friend.ClassYear }}</td>
          <td class="table-secondary">{{ friend.hobby }}</td>
          <td class="table-info">{{ friend.food }}</td>
          <td class="table-secondary">{{ friend.drink }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <a href="{% url 'homepage:addfriend' %}" style="text-decoration: none;"> 
    <button id="friendButton" type="button" class="btn btn-light">
      Add Friends</button> </a>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>